### ISSUE TITLE
INTERPRET-AS-MONTH broken in LispWorks because WHEN-LET is not visible

### ISSUE THREAD

**Issue by CK-DE** [stacksmith/trivial-rfc-1123#3]
In LispWorks 7.2.1 (and probably other versions as well) INTERPRET-AS-MONTH doesn't work because WHEN-LET is unknown in package "TRIVIAL-RFC-1123". This is because WHEN-LET is defined in the "LISPWORKS" package and therefore not made visible by having (:use #:cl) in the package definition.

May I kindly ask you to fix this?

**Comment by stacksmith** [comment]
Fixed.  I think.

**Comment by CK-DE** [comment]
Fixed! Thank a lot.
